server:
  port: 9393

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
          git:
             uri: https://github.com/imarungupta/config-server    # Placed common configuration
             clone-on-start: true

# Now every microservice's need to communicate with this config server and for that let's include config-client
# dependencies and @EnableConfigClient in each microservice

#  <dependency>
#     <groupId>org.springframework.cloud</groupId>
#      <artifactId>spring-cloud-starter-config</artifactId>
#  </dependency>

# Enabling config-server in each service so that common configuration can be added from GitHub
# spring.cloud.config:enabled: true
# spring.cloud.config:uri: http://localhost:9393

# Instead of adding in each file let's create bootstrap.yml and add this configuration
#-------------------------------------------------

# Comment this below eureka client configuration in each service because now we start reading from config-server > GitHub
# Let's configure the below common properties in github repo and read from there in each application

#eureka.client.register-with-eureka: true
#eureka.client.fetch-registry: true
#eureka.client.service-url.defaultzone: http://localhost:8761/eureka/
#eureka.client.instance.hostname: localhost
