server:
  port: 9001

spring:
  application.name: DEPARTMENT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud_db
    username: root
    password: Admin@123
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect



#zipkin:
#  base-url: http://127.0.0.1:9411/

# Enabling config-server in each service so that common configuration can be added from GitHub
# spring.cloud.config:enabled: true
# spring.cloud.config:uri: http://localhost:9393

# Instead of adding in each file let's create bootstrap.yml and add this configuration
#-------------------------------------------------

# Comment this below eureka client configuration in each service because now we start reading from config-server > GitHub

#eureka.client.register-with-eureka: true
#eureka.client.fetch-registry: true
#eureka.client.service-url.defaultzone: http://localhost:8761/eureka/
#eureka.client.instance.hostname: localhost
