server:
  port: 8181

spring:
  application:
    name: JWT-SPRING-SECURITY

  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud_db
    username: root
    password: Admin@123

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
